import { mutation } from "./_generated/server";

export const seedFacilities = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("facilities").first();
    if (existing) return { message: "already seeded" };

    const facilities = [
      // 複合商業施設
      {
        name: "イオンモール多摩平の森",
        category: "complex" as const,
        address: "東京都日野市多摩平2-2",
        prefecture: "東京都",
        city: "日野市",
        lat: 35.6712,
        lng: 139.3899,
        website: "https://tamadaira.aeon.jp",
        hours: "10:00〜21:00",
        parkingCategory: "B" as const,
        parkingDetails: {
          totalSpaces: 2100,
          freeCondition: "ショッピング利用で無料",
          freeMinutes: 180,
          paidRate: "以降30分100円",
          notes: "映画館利用は別途無料時間加算あり",
        },
        source: "seed",
      },
      {
        name: "ららぽーと立川立飛",
        category: "complex" as const,
        address: "東京都立川市泉町935-1",
        prefecture: "東京都",
        city: "立川市",
        lat: 35.7197,
        lng: 139.4162,
        website: "https://mitsui-shopping-park.com/lalaport/tachihi/",
        hours: "10:00〜21:00",
        parkingCategory: "B" as const,
        parkingDetails: {
          totalSpaces: 3200,
          freeCondition: "施設利用で最大3時間無料",
          freeMinutes: 180,
          paidRate: "以降30分200円",
        },
        source: "seed",
      },
      {
        name: "イーアスTAKAO",
        category: "complex" as const,
        address: "東京都八王子市みなみ野1-7-1",
        prefecture: "東京都",
        city: "八王子市",
        lat: 35.6282,
        lng: 139.3127,
        website: "https://www.ias-takao.jp",
        hours: "10:00〜21:00",
        parkingCategory: "B" as const,
        parkingDetails: {
          totalSpaces: 2000,
          freeCondition: "レシート提示で3時間無料",
          freeMinutes: 180,
          paidRate: "以降30分100円",
        },
        source: "seed",
      },
      // スーパー・量販店
      {
        name: "コストコホールセール多摩境店",
        category: "supermarket" as const,
        address: "東京都町田市小山ヶ丘1-7-1",
        prefecture: "東京都",
        city: "町田市",
        lat: 35.5856,
        lng: 139.4199,
        website: "https://www.costco.co.jp",
        hours: "10:00〜20:00",
        parkingCategory: "B" as const,
        parkingDetails: {
          totalSpaces: 800,
          freeCondition: "会員購入で無料",
          notes: "会員証が必要",
        },
        source: "seed",
      },
      {
        name: "IKEA立川",
        category: "supermarket" as const,
        address: "東京都立川市栄町6-2-1",
        prefecture: "東京都",
        city: "立川市",
        lat: 35.6982,
        lng: 139.4161,
        website: "https://www.ikea.com/jp/ja/stores/tachikawa/",
        hours: "10:00〜21:00",
        parkingCategory: "C" as const,
        parkingDetails: {
          totalSpaces: 1200,
          freeCondition: "IKEA Family会員で最大3時間無料",
          freeMinutes: 180,
          paidRate: "以降30分300円",
        },
        source: "seed",
      },
      // 博物館・美術館
      {
        name: "国立科学博物館",
        category: "museum" as const,
        address: "東京都台東区上野公園7-20",
        prefecture: "東京都",
        city: "台東区",
        lat: 35.7167,
        lng: 139.7753,
        website: "https://www.kahaku.go.jp",
        hours: "9:00〜17:00（土日祝〜18:00）",
        parkingCategory: "D" as const,
        parkingDetails: {
          totalSpaces: 40,
          paidRate: "30分100円",
          notes: "駐車場はこはく の広場駐車場を利用",
        },
        source: "seed",
      },
      {
        name: "江戸東京博物館",
        category: "museum" as const,
        address: "東京都墨田区横網1-4-1",
        prefecture: "東京都",
        city: "墨田区",
        lat: 35.6966,
        lng: 139.7954,
        website: "https://www.edo-tokyo-museum.or.jp",
        hours: "9:30〜17:30（土曜〜19:30）",
        parkingCategory: "D" as const,
        parkingDetails: {
          totalSpaces: 130,
          paidRate: "1時間200円、以降30分100円",
        },
        source: "seed",
      },
      {
        name: "東京都現代美術館",
        category: "museum" as const,
        address: "東京都江東区三好4-1-1",
        prefecture: "東京都",
        city: "江東区",
        lat: 35.6826,
        lng: 139.7983,
        website: "https://www.mot-art-museum.jp",
        hours: "10:00〜18:00",
        parkingCategory: "D" as const,
        parkingDetails: {
          totalSpaces: 80,
          paidRate: "1時間200円",
        },
        source: "seed",
      },
      // 温泉
      {
        name: "東京都市大学等々力キャンパス温泉（等々力温泉）",
        category: "onsen" as const,
        address: "東京都世田谷区等々力8-10-1",
        prefecture: "東京都",
        city: "世田谷区",
        lat: 35.6105,
        lng: 139.6555,
        hours: "12:00〜24:00",
        parkingCategory: "B" as const,
        parkingDetails: {
          totalSpaces: 50,
          freeCondition: "温泉利用で2時間無料",
          freeMinutes: 120,
          paidRate: "以降30分200円",
        },
        source: "seed",
      },
      {
        name: "大江戸温泉物語 東京",
        category: "onsen" as const,
        address: "東京都江東区青海2-6-3",
        prefecture: "東京都",
        city: "江東区",
        lat: 35.6285,
        lng: 139.7765,
        website: "https://ooedoonsen.jp/tokyo/",
        hours: "11:00〜翌9:00",
        parkingCategory: "C" as const,
        parkingDetails: {
          totalSpaces: 120,
          freeCondition: "施設利用で2時間無料",
          freeMinutes: 120,
          paidRate: "以降30分200円",
        },
        source: "seed",
      },
      // 公園・アウトドア
      {
        name: "昭和記念公園",
        category: "park" as const,
        address: "東京都立川市緑町3173",
        prefecture: "東京都",
        city: "立川市",
        lat: 35.7053,
        lng: 139.4053,
        website: "https://www.showakinen-koen.jp",
        hours: "9:30〜17:00（季節変動あり）",
        parkingCategory: "D" as const,
        parkingDetails: {
          totalSpaces: 1650,
          paidRate: "1時間310円（普通車）",
          notes: "公園入園料別途必要",
        },
        source: "seed",
      },
      {
        name: "井の頭恩賜公園",
        category: "park" as const,
        address: "東京都武蔵野市御殿山1-18-31",
        prefecture: "東京都",
        city: "武蔵野市",
        lat: 35.7008,
        lng: 139.5726,
        website: "https://www.kensetsu.metro.tokyo.lg.jp/jimusho/seibuk/inokashira/index.html",
        hours: "終日開放",
        parkingCategory: "D" as const,
        parkingDetails: {
          totalSpaces: 200,
          paidRate: "1時間200円",
        },
        source: "seed",
      },
      // 動物園・水族館
      {
        name: "葛西臨海水族園",
        category: "zoo" as const,
        address: "東京都江戸川区臨海町6-2-3",
        prefecture: "東京都",
        city: "江戸川区",
        lat: 35.6481,
        lng: 139.8591,
        website: "https://www.tokyo-zoo.net/zoo/kasai/",
        hours: "9:30〜17:00",
        parkingCategory: "D" as const,
        parkingDetails: {
          totalSpaces: 502,
          paidRate: "1時間200円（最大600円）",
        },
        source: "seed",
      },
      {
        name: "多摩動物公園",
        category: "zoo" as const,
        address: "東京都日野市程久保7-1-1",
        prefecture: "東京都",
        city: "日野市",
        lat: 35.6536,
        lng: 139.4093,
        website: "https://www.tokyo-zoo.net/zoo/tama/",
        hours: "9:30〜17:00",
        parkingCategory: "D" as const,
        parkingDetails: {
          totalSpaces: 850,
          paidRate: "1時間200円（最大600円）",
        },
        source: "seed",
      },
      // ホームセンター
      {
        name: "カインズホーム東大和店",
        category: "homeimprovement" as const,
        address: "東京都東大和市桜が丘2-276",
        prefecture: "東京都",
        city: "東大和市",
        lat: 35.7334,
        lng: 139.4296,
        website: "https://www.cainz.com",
        hours: "9:00〜21:00",
        parkingCategory: "B" as const,
        parkingDetails: {
          totalSpaces: 350,
          freeCondition: "買い物で無料",
          notes: "無料時間制限なし（閉店まで）",
        },
        source: "seed",
      },
      // 映画館・レジャー
      {
        name: "TOHOシネマズ府中",
        category: "cinema" as const,
        address: "東京都府中市宮西町2-1-2",
        prefecture: "東京都",
        city: "府中市",
        lat: 35.6681,
        lng: 139.4793,
        website: "https://tohotheater.jp/theater/find/076_top.html",
        hours: "上映スケジュールによる",
        parkingCategory: "C" as const,
        parkingDetails: {
          totalSpaces: 700,
          freeCondition: "映画1本鑑賞で3時間無料",
          freeMinutes: 180,
          paidRate: "以降30分100円",
        },
        source: "seed",
      },
      // 道の駅
      {
        name: "道の駅 八王子滝山",
        category: "roadstop" as const,
        address: "東京都八王子市滝山町1-592-2",
        prefecture: "東京都",
        city: "八王子市",
        lat: 35.6763,
        lng: 139.3254,
        website: "https://www.michinoeki-takiyama.jp",
        hours: "9:00〜18:00",
        parkingCategory: "A" as const,
        parkingDetails: {
          totalSpaces: 168,
          notes: "完全無料・24時間利用可",
        },
        source: "seed",
      },
      // 図書館・公共施設
      {
        name: "武蔵野市立武蔵野プレイス",
        category: "library" as const,
        address: "東京都武蔵野市境南町2-3-18",
        prefecture: "東京都",
        city: "武蔵野市",
        lat: 35.7027,
        lng: 139.5622,
        website: "https://www.musashino-place.jp",
        hours: "9:00〜22:00",
        parkingCategory: "B" as const,
        parkingDetails: {
          totalSpaces: 30,
          freeCondition: "図書館・施設利用で2時間無料",
          freeMinutes: 120,
          paidRate: "以降30分200円",
        },
        source: "seed",
      },
      // 農産物直売所
      {
        name: "JAファーマーズマーケット ファームサイドみのり",
        category: "farm" as const,
        address: "東京都日野市程久保2-26-1",
        prefecture: "東京都",
        city: "日野市",
        lat: 35.6572,
        lng: 139.4027,
        hours: "9:00〜17:00（火定休）",
        parkingCategory: "A" as const,
        parkingDetails: {
          totalSpaces: 60,
          notes: "買い物不要でも無料",
        },
        source: "seed",
      },
    ];

    let count = 0;
    for (const facility of facilities) {
      await ctx.db.insert("facilities", {
        ...facility,
        scrapedAt: Date.now(),
        isVerified: true,
        isActive: true,
      });
      count++;
    }

    return { message: `seeded ${count} facilities` };
  },
});
